name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build Simulator
      run: xcodebuild clean build test -workspace Example/QBToast.xcworkspace -scheme "QBToast-Example" -sdk iphonesimulator -destination "platform=iOS Simulator, id:3A32AE24-6F29-47AC-9A3E-F891CA7096F3, OS:14.4, name:iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
