name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select --switch /Library/Developer/CommandLineTools
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
